name: Build and Deploy Frontend

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/build-and-deploy-frontend.yml"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{secrets.GCP_PROJECT_ID }}
          service_account_key: ${{secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Docker auth to Artifact Registry
        run: |
          gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/frontend:latest ./frontend

      - name: Push Docker image
        run: |
          docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/frontend:latest

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
