name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: YOUR_PROJECT_ID
  REGION: europe-central2
  REPO: guessing-micro-full

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          # service_account_key: ${{ secrets.GCP_SA_KEY }}
          # export_default_credentials: true

      - name: Build & push game-service
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO }}-game ./services/game-service

      - name: Deploy game-service to Cloud Run
        run: |
          gcloud run deploy game-service             --image gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO }}-game             --region=${{ env.REGION }} --platform=managed --allow-unauthenticated

      - name: Build & push score-service
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO }}-score ./services/score-service

      - name: Deploy score-service to Cloud Run
        run: |
          gcloud run deploy score-service             --image gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO }}-score             --region=${{ env.REGION }} --platform=managed --allow-unauthenticated
