name: Build & Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: flask-kube-joc
  REGION: europe-central2
  REPO: guessing-micro-full
  CLUSTER: flask-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          # service_account_key: ${{ secrets.GCP_SA_KEY }}
          # export_default_credentials: true

      - name: Configure docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build and push game image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/game-service:$GITHUB_SHA ./services/game-service
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/game-service:$GITHUB_SHA

      - name: Build and push score image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/score-service:$GITHUB_SHA ./services/score-service
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/score-service:$GITHUB_SHA

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${CLUSTER} --zone=${REGION}-a

      - name: Update k8s images and apply
        run: |
          sed -i "s|YOUR_PROJECT_ID|${PROJECT_ID}|g" k8s/*.yaml || true
          kubectl apply -f k8s/
          kubectl set image deployment/game-service game=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/game-service:$GITHUB_SHA
          kubectl set image deployment/score-service score=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/score-service:$GITHUB_SHA
