name: Deploy Infra + App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: flask-kube-joc
  REGION: europe-central2
  REPO_NAME: python_service
  CLUSTER_NAME: flask-cluster
  DEPLOYMENT_NAME: flask-app
  IMAGE_NAME: flask-kube
  PROJECT_NUMBER: 254093640083
  GCP_SA_KEY: NA

jobs:
  infra:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

  deploy:
    name: Build, Push, and Deploy to GKE
    runs-on: ubuntu-latest
    needs: infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone=${{ env.REGION }}-a

      - name: Deploy to GKE
        run: |
          sed -i "s|YOUR_PROJECT_ID|${{ env.PROJECT_ID }}|g" kubernetes/deployment.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} flask-container=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Configure monitoring (Prometheus + Grafana)
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
   
