name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: YOUR_PROJECT_ID
  REGION: europe-central2
  REPO_NAME: flask-kube-gcp
  CLUSTER_NAME: flask-cluster
  DEPLOYMENT_NAME: flask-app
  IMAGE_NAME: flask-kube

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.flask-kube-gcp }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.flask-kube-gcp }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone=${{ env.REGION }}-a

    - name: Deploy to GKE
      run: |
        sed -i "s|YOUR_PROJECT_ID|${{ env.PROJECT_ID }}|g" kubernetes/deployment.yaml
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} flask-container=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.flask-kube-gcp }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
