name: Build & Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "guessing-micro-full/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: "access_token"

    - name: Configure Docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

    - name: Build & Push
      run: |
        docker build \
          -t europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/frontend:latest \
          ./guessing-micro-full/frontend

        docker push \
          europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/frontend:latest

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials guessing-cluster \
          --zone europe-central2-a \
          --project flask-kube-joc

    - name: Install GKE Auth Plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Deploy to GKE
      run: |
        kubectl rollout restart deployment frontend
