name: Build & Deploy Score-Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "guessing-micro-full/services/score-service/**"
      - ".github/workflows/build-and-deploy-score-service.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: "access_token"

    - name: Configure Docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

    - name: Build & Push Docker Image
      run: |
        docker build \
          -t europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/score-service:latest \
          ./guessing-micro-full/services/score-service

        docker push \
          europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/score-service:latest

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials guessing-cluster \
          --zone europe-central2-a \
          --project flask-kube-joc

    - name: Deploy to GKE
      run: |
        kubectl rollout restart deployment score-service
