name: Build & Deploy Gateway

on:
  push:
    branches: [ "main" ]
    paths:
      - "guessing-micro-full/services/gateway/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: "access_token"

    - name: Configure Docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

    - name: Build & Push
      run: |
        docker build \
          -t europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/gateway:latest \
          ./guessing-micro-full/services/gateway

        docker push \
          europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/gateway:latest

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials guessing-cluster \
          --zone europe-central2-a \
          --project flask-kube-joc

    - name: Install GKE Auth Plugin
      run: |
        echo "Adding Google Cloud SDK repository"
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
          | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
          | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin


    - name: Deploy to GKE
      run: |
        kubectl rollout restart deployment gateway
