name: Build & Deploy Gateway

on:
  push:
    branches: [ "main" ]
    paths:
      - "guessing-micro-full/gateway/**"
      - ".github/workflows/build-and-deploy-gateway.yaml"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: "access_token"

    - name: Configure Docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

    - name: Build & Push
      run: |
        docker build \
          -t europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/gateway:latest \
          ./guessing-micro-full/services/gateway

        docker push \
          europe-central2-docker.pkg.dev/flask-kube-joc/my-repo/gateway:latest

    - name: Install GKE Auth Plugin
      run: |
        gcloud components update --quiet
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Configure kubectl
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials guessing-cluster \
          --zone europe-central2-a \
          --project flask-kube-joc

    - name: Deploy to GKE
      run: |
        kubectl rollout restart deployment gateway
