name: Build & Deploy Gateway

on:
  push:
    paths:
      - "gateway/**"
      - ".github/workflows/build-and-deploy-gateway.yaml"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - run: docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/gateway:latest ./gateway

      - run: docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/gateway:latest

      - run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f k8s/gateway-deployment.yaml
          kubectl apply -f k8s/gateway-service.yaml
